# config.yaml
# Copyright 2024 Keith Maxwell
# SPDX-License-Identifier: MPL-2.0
config:
  cloud-init.user-data: |
    #cloud-config
    package_update: true
    package_upgrade: true
    packages: [inkscape]
devices:
  eth0:
    name: eth0
    type: nic
    network: lxdbr0
  root:
    path: /
    pool: default
    type: disk
