version = 1
SPDX-PackageName = "icons"
SPDX-PackageSupplier = "Keith Maxwell <keith.maxwell@gmail.com>"
SPDX-PackageDownloadLocation = "https://github.com/maxwell-k/icons"

[[annotations]]
path = [".en.utf-8.add", ".gitignore"]
SPDX-FileCopyrightText = "2023 Keith Maxwell"
SPDX-License-Identifier = "CC0-1.0"

# REUSE.toml
# Copyright 2024 Keith Maxwell
# SPDX-License-Identifier: CC0-1.0
